server.port=8002

spring.application.name=market-api

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m

market.dataset-path=${MARKET_DATASET_PATH:../../data/House Price Dataset.csv}

ml.api-url=${ML_API_URL:http://127.0.0.1:8000}
